import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'


const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ptbr" className='h-full bg-gray-100'>
      <body className={roboto.className}>
        <main className='h-full'>
          <Header />
          {children}
        </main>
      </body>
    </html>
  )
}
